### PR TITLE
Add Projects to a QFROUND with a virtual field for comma separated project_ids

### PR DESCRIPTION
**Pull request by CarlosQ96**
Improved adding projects in one go to a qfRound: https://github.com/Giveth/impact-graph/issues/1125

### CODE REVIEW

**Comment by CarlosQ96** [comment]
@maryjaf to add projects to the qfround fast just add a comma separated list to the textArea
image


To get the projects Ids, I recommend exporting to csv maybe with a filter.
image

Clicking the Export filter to csv button. This shouuld put all projects in a csv with the ids.

**Comment by CarlosQ96** [comment]
The text area is only available when editting a QfRound, so go into qfRoundTab, select the round you want => edit.

**Comment by CarlosQ96** [comment]
It will only allow this if the round is active, ended rounds will be ignored adding new projects to them.

**Review by jainkrati — APPROVED** [review]

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @CarlosQ96  LGTM

**Pull request merged**
