### PR TITLE
Feat/unverified project boost amount

### PR DESCRIPTION
**Pull request by aminlatifi**
https://github.com/Giveth/GIVeconomy/issues/739

### CODE REVIEW

**Comment by aminlatifi** [comment]
@mohammadranjbarz I changed the migration file name to make it run again! do you think it can work? I thought it can be a better idea rather than having two migration files for single action

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz I changed the migration file name to make it run again! do you think it can work? I thought it can be a better idea rather than having two migration files for single action

Good idea, I think it's better

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @aminlatifi  LGTM

**Comment by aminlatifi** [comment]
Ok, merged it. @mohammadranjbarz Please have a look on the deploy and migrations

**Comment by mohammadranjbarz** [comment]
> Ok, merged it. @mohammadranjbarz Please have a look on the deploy and migrations

Screen Shot 1401-08-09 at 11 23 32

Thanks @aminlatifi everything seems good


@maryjaf  You can test it on UAT now

**Pull request merged**
