### PR TITLE
F 77 fix migrations for test

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
related to #77

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 
I have deleted useless migrations( Because they made needed changes, and we don't need the anymore), for sratup we just need two migrations , and from now on our migrations should be executed during CI/CD, so we can't write a migration file that users with clean DB have problem with running that

**Review by CarlosQ96 — APPROVED** [review]
I tested locally migrating my db with fresh dbs with some data, and it works fine.
However, we should proceed to test on the dev server, just to see there aren't conflicts running migrations. After that let's merge. 
(btw, I think the dev server is not deploying correctly tho, gets stuck).

**Comment by mohammadranjbarz** [comment]
> I tested locally migrating my db with fresh dbs with some data, and it works fine. However, we should proceed to test on the dev server, just to see there aren't conflicts running migrations. After that let's merge. (btw, I think the dev server is not deploying correctly tho, gets stuck).

Thanks Carlos, you are right, Develop has problem

@geleeroyale Can you create a db connection for develop environment, and import DB data of develop env to that?
dev server: dev.serve.giveth.io

**Comment by geleeroyale** [comment]
Dev.serve has been migrated successfully to a hosted database.

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 

I have merged this branch to develop and it went right, I merge this just now

**Pull request merged**
