### PR TITLE
Release: Add isactive and fix adminjs for categories (#1223)

### PR DESCRIPTION
**Pull request by CarlosQ96**
Hotfix for categories in the polygon round, afterwards we can create those categories manually

### CODE REVIEW

**Comment by CarlosQ96** [comment]
@mohammadranjbarz Ramin is working on this, I think he could potentially release tomorrow, if you can release this, would appreciate it.

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 
Sure man
@RamRamez I will merge it when you tell me

**Comment by RamRamez** [comment]
> @CarlosQ96 Sure man @RamRamez I will merge it when you tell me

@mohammadranjbarz I think we can release backend and front-end separately, so feel free to merge it

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @CarlosQ96  LGTM

**Pull request merged**
