### PR TITLE
Allow to set the matching pool token & amount to be something other than usd

### PR DESCRIPTION
**Pull request by RamRamez**
https://github.com/Giveth/giveth-dapps-v2/issues/3839

### CODE REVIEW

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @RamRamez , LGTM

**Comment by mohammadranjbarz** [comment]
@RamRamez Ooops, the tests have failed

**Review by CarlosQ96 — APPROVED** [review]
LGTM! Thanks Ramin

**Review by jainkrati — APPROVED** [review]

**Review by CarlosQ96 — APPROVED** [review]
LGTM!

**Pull request merged**
