### PR TITLE
Add gitcoin adapter for integration

### PR DESCRIPTION
**Pull request by CarlosQ96**
Related to: https://github.com/Giveth/impact-graph/issues/987

### CODE REVIEW

**Comment by CarlosQ96** [comment]
When you can review and merge Mohammad to your branch, you can use the gitcoin api.

**Comment by CarlosQ96** [comment]
You can get the api keys by following the beginning of this guide https://docs.passport.gitcoin.co/building-with-passport/quick-start-guide
The registration of the passport is a bit tricky im not sure if the frontend implemented the auth for it yet. But i merged Amin's Pr to staging/develop of the authe microservice for passport submitting and nonce generation

**Comment by CarlosQ96** [comment]
Endpoint Definition which I based the interfaces off: https://docs.passport.gitcoin.co/building-with-passport/scorer-api/endpoint-definition

**Comment by CarlosQ96** [comment]
I tested manually the api and error results and data, but the test is for the query functionality mostly.

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @CarlosQ96 LGTM

**Pull request merged**
