### PR TITLE
Feature add optimism tokens

### PR DESCRIPTION
**Pull request by CarlosQ96**
Related to: https://github.com/Giveth/giveth-dapps-v2/issues/2495
and taken from monoswap pr: https://github.com/Giveth/monoswap/pull/9/files

Tokens excluded: RAI, ALUSD, KWENTA and BOB
This do no return correct values.

### CODE REVIEW

**Comment by CarlosQ96** [comment]
image

**Comment by CarlosQ96** [comment]
These are the 13 tokens, bu removing the 4 that dont return correct values the migration adds 9. 
https://forum.giveth.io/t/givbacks-token-list/253/28?u=mateodaza

**Comment by CarlosQ96** [comment]
@aminlatifi we are running migration manually when deploying right?

**Review by aminlatifi — APPROVED** [review]
LGTM, thanks @CarlosQ96

**Comment by aminlatifi** [comment]
> @aminlatifi we are running migration manually when deploying right?

Yes, it's part of docker start

**Pull request merged**
