### PR TITLE
Add Goerli network

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
related to #597

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
@mateodaza  have you done the frontend side?
is it safe to merge backend side? ( although I tried to make it backward compatible to still work with Ropsten network)

**Comment by MoeNick** [comment]
I think the donation flow also should be considered.

**Comment by mateodaza** [comment]
@mohammadranjbarz this is essentially for the donation flow. GIVeconomy network is already migrated - So I think it's safe to merge as most of the config comes from the backend

**Review by CarlosQ96 — APPROVED** [review]
Checked tests and migrations, everything seems ok! LGTM the code. 

I think we can skip giving blocks for tests/goerli as we really don't see much use from them, we are kind of wanting to unintegrate, so not worth the effort.

**Pull request merged**
