### PR TITLE
Remove donations relation from projectById query

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
related to #238

joining donations to project table cause disaster in production ENV
so I have removed that relation

### CODE REVIEW

**Review by CarlosQ96 — APPROVED** [review]
Agree! We ended up removing donations relation from all posible endpoints. 😆

**Comment by mohammadranjbarz** [comment]
@RamRamez 
If you use donations for `projectById` query, be careful and change it please

**Comment by mohammadranjbarz** [comment]
@RamRamez 
If you use donations for `projectById` query, be careful and change it please

**Comment by mohammadranjbarz** [comment]
> @RamRamez If you use donations for `projectById` query, be careful and change it please

@RamRamez  I assume you don't use it, so I will merge this PR

**Comment by RamRamez** [comment]
> > @RamRamez If you use donations for `projectById` query, be careful and change it please
> 
> @RamRamez I assume you don't use it, so I will merge this PR

I think we are not using `projectById` at all

**Comment by CarlosQ96** [comment]
Mateo is using it in the last release. But donations is not being used, so it's alright.

**Pull request merged**
