### PR TITLE
Hotfix: Add validation for project statuses for project feed

### PR DESCRIPTION
**Pull request by CarlosQ96**
Related to: https://github.com/Giveth/impact-graph/issues/751

### CODE REVIEW

**Comment by MoeNick** [comment]
@mohammadranjbarz pls check it out

**Review by mohammadranjbarz — APPROVED** [review]
@CarlosQ96  Thank you, LGTM

**Comment by mohammadranjbarz** [comment]
@maryjaf  I merged it, it would be on Staging in 15 minutes

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz It has been resolved

**Pull request merged**
