### PR TITLE
Add projectlink to project show page in adminbro

### PR DESCRIPTION
**Pull request by CarlosQ96**
Related to: https://github.com/Giveth/impact-graph/issues/642

Mini quality of life for communication/projectverification team.

### CODE REVIEW

**Comment by CarlosQ96** [comment]
Screenshot of result:
image

All envs have the env var GIVETH_IO_DAPP_BASE_URL, but if you don't you gotta set it.

**Comment by CarlosQ96** [comment]
/project/ is the correct url, just pushed that fix haha not like the image, but the image is to get the idea.

**Comment by CarlosQ96** [comment]
Link is clickable.

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @CarlosQ96  LGTM

**Pull request merged**
