### PR TITLE
F 579 multi filters

### PR DESCRIPTION
**Pull request by CarlosQ96**
Related to https://github.com/Giveth/impact-graph/issues/579

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  I have a suggestion, we can keep the `projects` query and for these change implement a new query based on `projects` to be backward compatible, after frontend implemented the client side we can remove old query, what do you think?

**Comment by CarlosQ96** [comment]
Thanks Mohammad! I think it's wise to do that. I shall do it, I would then leave the original query alone and move all to another one.

**Comment by CarlosQ96** [comment]
I think the implementation changed a bit but its simpler for the frontend.
Query Examples:
SortingBy values = Newest, Oldest, MostFunded, MostLiked
Filters array values = Verified, AcceptGiv, Traceable, GivingBlock
```
query {
  allProjects(take: 10, skip: 0, sortingBy: Oldest, filters: [AcceptGiv]) {
    projects {
      id
      title
      verified
      givingBlocksId
      donations {
        valueUsd
      }
      creationDate
    }
    totalCount
    categories {
      name
    }
  }
}
```

**Comment by CarlosQ96** [comment]
Full Query definition:
```
 query (
    $take: Int
    $skip: Int
    $sortingBy: SortingField
    $filters: [FilterField!]
    $searchTerm: String
    $category: String
    $mainCategory: String
    $connectedWalletUserId: Int
  ) {
    allProjects(
      take: $take
      skip: $skip
      sortingBy: $sortingBy
      filters: $filters
      searchTerm: $searchTerm
      category: $category
      mainCategory: $mainCategory
      connectedWalletUserId: $connectedWalletUserId
    ) {
      projects {
        id
        title
        balance
        image
        slug
        creationDate
        updatedAt
        admin
        description
        walletAddress
        impactLocation
        qualityScore
        verified
        traceCampaignId
        listed
        givingBlocksId
        status {
          id
          symbol
          name
          description
        }
        categories {
          name
          mainCategory {
            title
            slug
            banner
            description
          }
        }
        reaction {
          id
        }
        adminUser {
          id
          email
          firstName
          walletAddress
        }
        organization {
          name
          label
          supportCustomTokens
        }
        addresses {
          address
          isRecipient
          networkId
        }
        totalReactions
        totalDonations
        totalTraceDonations
      }
      totalCount
      categories {
        name
      }
    }
  }
```

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @CarlosQ96 LGTM, I just modified and improved test cases, other things was fine

**Pull request merged**
