### PR TITLE
Add Giv-Arb Missing Donations

### PR DESCRIPTION
**Pull request by RamRamez**

### CODE REVIEW

**Review by mohammadranjbarz — APPROVED** [review]
LGTM @RamRamez thanks, just you haven't add them to the qfRound, I will do it manually in DB

**Comment by koday1** [comment]
Hey @mohammadranjbarz @RamRamez is this all sorted out? I am waiting to make sure we have all the donations counted before doing the data analysis for the GIV-ARB round. Let me know, thanks

**Comment by RamRamez** [comment]
@koday1 there's another ticket related to missing donations. I'm preparing the PR. I'll send updates here when it's merged.

UPDATE: it's done

**Comment by koday1** [comment]
Thank you @RamRamez !

**Pull request merged**
