### PR TITLE
Fix projects query

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
The backend kept eating memory and restarting in production, after monitoring DB logs I found the `donations` join is very expensive so we have to delete that

### CODE REVIEW

**Review by CarlosQ96 — APPROVED** [review]
I agree, I think @RamRamez should confirm with us first if he doesn't use that included data.

**Comment by RamRamez** [comment]
@mohammadranjbarz @CarlosQ96 What query is removed?

The `donations` object in `projectBySlug`?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz @CarlosQ96 What query is removed?
> 
> The `donations` object in `projectBySlug`?

No in `projects`
I think it's not needed in frontend because staging is up and running

**Comment by CarlosQ96** [comment]
In the all projects query (with all the filters/searching etc) we removed the donations because it was causing a memory leak.

**Pull request merged**
