### PR TITLE
Add filters for qfrounds for project donation page

### PR DESCRIPTION
**Pull request by CarlosQ96**
Filter by QfRoundId 
Related to: https://github.com/Giveth/giveth-dapps-v2/issues/2694

(ONLY the filters part, ill make a separated PR for the distributed matching, I think we can have a meeting about this tomorrow)

### CODE REVIEW

**Comment by CarlosQ96** [comment]
@alireza-sharifpour @MohammadPCh  to filter by qfround 
I added to the query 
```
export const fetchDonationsByProjectIdQuery = `
  query (
    $take: Int
    $skip: Int
    $traceable: Boolean
    $qfRoundId: Int
    $projectId: Int!
    $searchTerm: String
    $status: String
    $orderBy: SortBy
  ) {
    donationsByProjectId(
      take: $take
      skip: $skip
      traceable: $traceable
      qfRoundId: $qfRoundId
      projectId: $projectId
      searchTerm: $searchTerm
      status: $status
      orderBy: $orderBy
    ) {
      donations {
        id
        transactionId
        transactionNetworkId
        toWalletAddress
        fromWalletAddress
        currency
        anonymous
        valueUsd
        amount
        qfRound {
          id
        }
        status
        user {
          id
          walletAddress
          firstName
          email
        }
        createdAt
      }
      totalCount
      totalUsdBalance
    }
  }
`;
```
This argument
```
    @Arg('qfRoundId', type => Int, { defaultValue: null, nullable: true })

```

**Comment by CarlosQ96** [comment]
dont send the attribute if you want all donations

**Comment by CarlosQ96** [comment]
The ids are retrieves from the query qfRounds

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @CarlosQ96 
LGTM

**Pull request merged**
