### PR TITLE
Feature: Add eligible donations to qfround entity

### PR DESCRIPTION
**Pull request by CarlosQ96**
Related to the meeting we had. but I cant find the issue. Or if @laurenluz created it.

Can add array of networks to qfround and in the donation creation decides if marking or not

### CODE REVIEW

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @CarlosQ96  it's a great simple solution, just wondering if default value for eligileDonations should be empty array or an array of all supported networks, I'm worried about previous rounds

**Comment by CarlosQ96** [comment]
I thought about the empty state to reduce the workload for admins, and also instead of deleting each, just add those they want.

**Comment by mohammadranjbarz** [comment]
> I thought about the empty state to reduce the workload for admins, and also instead of deleting each, just add those they want.

You are right, so if you just modify the migration file to fill previous qfRounds eligibleNetworks to make sure we would not have any problem on them would be great

**Comment by CarlosQ96** [comment]
Ok ill add the migration tomorrow morning.

**Comment by CarlosQ96** [comment]
@mohammadranjbarz ready for final review and merging.

Also for frontend they should check the attribute
```eligibleNetworks``` in the graphql results in any query they fetch this info.

**Pull request merged**
