### PR TITLE
Reuse donation resolver

### PR DESCRIPTION
**Pull request by aminlatifi**
Refactored createBackupDonation to reuse resolver

### CODE REVIEW

**Comment by aminlatifi** [comment]
@mohammadranjbarz @CarlosQ96 I haven't tested it, do you think it would work?

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @aminlatifi now it's much cleaner and better.
I added a test case and fixed the function

**Comment by aminlatifi** [comment]
> Thanks @aminlatifi now it's much cleaner and better. I added a test case and fixed the function

Thanks @mohammadranjbarz 

@CarlosQ96 Please review this and if it is approved, feel free to merge this and https://github.com/Giveth/impact-graph/pull/1253
Then keep an eye on staging to see the import is working well.

**Comment by aminlatifi** [comment]
@CarlosQ96 I had to merge this, since further update fo #1253 would cause conflict

**Pull request merged**
