### PR TITLE
Add donation flow diagram

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
related to #295

@CarlosQ96  @mateodaza 
I would appreciate if both of you review this diagram

### CODE REVIEW

**Review by CarlosQ96 — APPROVED** [review]
I would add the totalDonations update to the diagram indicating after updating the priceUSD the whole projects total donations is recalculated. 

Aside from that I think it's great documentation!

**Comment by mohammadranjbarz** [comment]
> I would add the totalDonations update to the diagram indicating after updating the priceUSD the whole projects total donations is recalculated.
> 
> Aside from that I think it's great documentation!

Good point
can you update it on this PR?
(You just click on the documentation, it would open it on mermaidjs editor, then change it and replace markdown link here)

**Comment by CarlosQ96** [comment]
Yes I'll do it today and update the PR.

**Comment by CarlosQ96** [comment]
Added! We can Merge!

**Comment by mohammadranjbarz** [comment]
> Added! We can Merge!

Thanks man

**Pull request merged**
