### PR TITLE
Fetch unlisted projects

### PR DESCRIPTION
**Pull request by MohammadPCh**
- Giveth/DeVouch-BE#154

## Summary by CodeRabbit

- **New Features**
	- Introduced an option to include unlisted projects in project queries.
	- Added a new parameter to filter project queries based on active status.

- **Bug Fixes**
	- Improved project filtering logic to accommodate the new inclusion parameter. 

- **Documentation**
	- Updated type signatures and class definitions to reflect new parameters.

### CODE REVIEW

**Comment by MohammadPCh** [comment]
@coderabbitai can you help me to write some tests for these changes?

**Comment by MohammadPCh** [comment]
i gonna write tests in `projectResolver.allProject.test.ts` file related to allProjects changes.

**Comment by MohammadPCh** [comment]
@coderabbitai ,  I want to write tests in `projectResolver.allProject.test.ts` file related to allProjects changes.

**Review by kkatusic — COMMENTED** [review]
LGTM ;), thx @MohammadPCh

**Review by kkatusic — APPROVED** [review]

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @MohammadPCh LGTM

**Pull request merged**
