### PR TITLE
Add data queries with data arrays by date

### PR DESCRIPTION
**Pull request by CarlosQ96**
No issue exists. This is for making a graph in the data dashboard created by Ramin. 
Url: https://analytics-dashboard-blue.vercel.app/

New updated queries and return data: (totalPerMonthAndYear is an array)
```
export const fetchTotalDonors = `
  query (
    $fromDate: String
    $toDate: String
  ) {
    totalDonorsCountPerDate(
      fromDate: $fromDate
      toDate: $toDate
    ) {
      total
      totalPerMonthAndYear {
        total
        date
      }
    }
  }
`;

export const fetchTotalDonationsUsdAmount = `
  query (
    $fromDate: String
    $toDate: String
  ) {
    donationsTotalUsdPerDate (
      fromDate: $fromDate
      toDate: $toDate
    ) {
      total
      totalPerMonthAndYear {
        total
        date
      }
    }
  }

export const fetchNewProjectsPerDate = `
  query (
    $fromDate: String
    $toDate: String
  ) {
    projectsPerDate(
      fromDate: $fromDate
      toDate: $toDate
    ) {
      total
      totalPerMonthAndYear {
        total
        date
      }
    }
  }
`;
`;
```

### CODE REVIEW

**Comment by CarlosQ96** [comment]
@RamRamez This is the Pr for the data arrays. The only query I did not return data array is for the totalDonationsPerCategory that you normalized. 
I think that query doesn't require it as it already has a normalized distribution graph. And it's quite complex to separate repeated data, which would still be somewhat inaccurate. 

If you think this is ok, let me know.

**Comment by CarlosQ96** [comment]
They are already sorted by date, oldest first.
Example Result:
```
{
   total: xxxx 
   totalPerMonthAndYear: [{ total: xxxx, date: '2021/1' }, { total: xxxx, date: '2022/2' }]
}
```

**Comment by CarlosQ96** [comment]
This is breaking changes, it will break staging dashboard. So once merged, Ramin must change it.

**Review by mohammadranjbarz — APPROVED** [review]
@CarlosQ96  Great job, I tested query and had correct result, 
LGTM

@RamRamez  As carlos said it had breaking change on dashboard, so we will merge it whenever you tell us

**Comment by RamRamez** [comment]
Great!
Thanks, @CarlosQ96 and @mohammadranjbarz for doing this.
The dashboard is currently connected to mainnet backend so you can safely merge this to staging.

**Pull request merged**
