### PR TITLE
Feat/transform base64 images in content/description

### PR DESCRIPTION
**Pull request by aminlatifi**
https://github.com/Giveth/impact-graph/issues/937

I forked from master branch

In the staging env, there are projects with base64 images in their description. Id of projects are: 78, 79, 97, 110

```sql
SELECT id, length("description") as content_length
FROM project
WHERE description LIKE '%;base64%'
order by content_length dESC nulls last
```

### CODE REVIEW

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @aminlatifi 
LGTM

**Comment by mohammadranjbarz** [comment]
I saved description of those four projects in my local machine, in case anything bad happened

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
migration execution got error in staging, please modify it and push again
If you want to see the logs you can go to staging server and enter 

`docker logs 9563e6c38950 -f`

Screen Shot 1402-01-15 at 11 21 20

**Comment by aminlatifi** [comment]
> 9563e6c38950

I restarted the docker and it seems it worked as expected

**Pull request merged**
