### PR TITLE
Disable dapp cors with envs

### PR DESCRIPTION
**Pull request by CarlosQ96**
Issue: https://github.com/Giveth/impact-graph/issues/1217

Moved the callback to it's own file, we should probably look into separating code from the bootstrap.ts, to prevent it from growing too much. Better separation of concerns.

### CODE REVIEW

**Comment by aminlatifi** [comment]
@mohammadranjbarz I think we must first merge the changes to staging to be sure it works fine

**Comment by CarlosQ96** [comment]
Ok we can merge to staging then.

**Comment by aminlatifi** [comment]
> Ok we can merge to staging then.

It's merged via https://github.com/Giveth/impact-graph/pull/1221

**Comment by CarlosQ96** [comment]
Can close this since we are making a release to master from staging

**Comment by CarlosQ96** [comment]
closing

**Pull request closed without merging**
