### PR TITLE
Fix running test without dropping db

### PR DESCRIPTION
**Pull request by mohammadranjbarz**

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
@aminlatifi  dropSchema works fine we just need to create `cronJob` db before running tests ( but when you change this and moving to givethio db, we can remove that as well)

**Comment by aminlatifi** [comment]
> @aminlatifi dropSchema works fine we just need to create `cronJob` db before running tests ( but when you change this and moving to givethio db, we can remove that as well)

I would put cronJob tables in the same db, not in a separate one. Though pg_cron extension creates the db iteself.

**Comment by mohammadranjbarz** [comment]
@aminlatifi  I updated typeorm and admin-bro, all tests pass but when I opened the admin bro I saw some issues that may take too much time but are necessary before merging

Screen Shot 1401-06-30 at 16 24 49

Screen Shot 1401-06-30 at 16 24 55

The relations don't work properly and when opening project page we get error, I think our custom views need to have some changes, so you tell me wether  it worth to put more time to finish that or not

**Comment by mohammadranjbarz** [comment]
@aminlatifi  I think we don't need this anymore, can we close it?

**Comment by aminlatifi** [comment]
@mohammadranjbarz Yes, we can close it. Thanks.

**Pull request closed without merging**
