### PR TITLE
Changed givpower boosting related queries to improve performance

### PR DESCRIPTION
**Pull request by aminlatifi**
Changed power_balance_snapshot table balance column to accept null values Change take TAKE_POWER_BOOSTING_SNAPSHOT procedure to make instances of power_balance_snapshot for users has power_boosting_snapshot for each snapshot Updated tests to match these changes
Ref #1067

### CODE REVIEW

**Comment by aminlatifi** [comment]
@CarlosQ96 @MohammadPCh We must monitor database load before and after this merge

**Comment by aminlatifi** [comment]
I noticed some of gnosis tests pass by setting xdai rpc to https://xdai-rpc.gateway.pokt.network/

**Comment by CarlosQ96** [comment]
@aminlatifi once I change the XDAI node url like you said the error is fixed.

If you look at the errors its a UNIQUENESS ERROR. Which doesn't make sense. But I encountered this before.

 I found the root cause, I think it's a bug in our test library.
When any http/blockchain/rpc call fails (in this case the xdai url), the tests retry themselves multiple times.
Since we don't clean the data on each test start it hit the uniqueness error.

We should update the test environment to this new url and rerun tests.

It's not the PRs issue but some network, xdai rpc url issue.

**Comment by CarlosQ96** [comment]
when changing Xdai url most tests worked but seems 2 are failing. Couldn't find the cause, if its still the xdai url or something else.

**Comment by aminlatifi** [comment]
@CarlosQ96 Let's raise the gnosis provider with the Devops team.
Did you review the PR? can we proceed? do you think we must wait for all tests be passed?

**Comment by CarlosQ96** [comment]
@aminlatifi I think all test need to pass or else it wont deploy. But I think the code is fine. 

Its a url/rpc issue not code.

**Review by CarlosQ96 — APPROVED** [review]
LGTM but we have to fix the URLS/RPC for tests to pass or wont deploy.

**Comment by CarlosQ96** [comment]
Locally all tests pass for me, its an rpc provider issue.

**Comment by CarlosQ96** [comment]
@geleeroyale @mhmdksh We are having some issue with the gnosis provider as it's not being reliable and failing when requesting data, throwing errors so our tests are failing.
We might need to find a new url or test won't pass.

**Comment by geleeroyale** [comment]
Hey Carlos! Which provider do we have set? If it is a gateway RPC I recommend to switch back to our quicknode instance

**Pull request merged**
