### PR TITLE
F 522 implement list countries webservice

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
related to #522

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  @RamRamez 

After merging this PR we can use this query
```
query {
    getAllowedCountries {
        name
        code
    }
}
```
but now we just use name of countries, and when filling organization country in backend we just accept countries from this list

**Review by CarlosQ96 — APPROVED** [review]
LGTM thanks man

**Comment by mohammadranjbarz** [comment]
> @CarlosQ96 @RamRamez
> 
> After merging this PR we can use this query
> 
> ```
> query {
>     getAllowedCountries {
>         name
>         code
>     }
> }
> ```
> 
> but now we just use name of countries, and when filling organization country in backend we just accept countries from this list

@alireza-sharifpour 
You can use this now

**Comment by alireza-sharifpour** [comment]
> > @CarlosQ96 @RamRamez
> > After merging this PR we can use this query
> > ```
> > query {
> >     getAllowedCountries {
> >         name
> >         code
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but now we just use name of countries, and when filling organization country in backend we just accept countries from this list
> 
> @alireza-sharifpour You can use this now

Thanks @mohammadranjbarz , it seems great, I will check them.

**Pull request merged**
