### PR TITLE
Solana user profile support

### PR DESCRIPTION
**Pull request by aminlatifi**
Save non-evm user wallet address capitalization

### CODE REVIEW

**Comment by aminlatifi** [comment]
Ref giveth/giveth-dapps-v2#3400

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @aminlatifi Seems good to me.
But tests haven't passed

**Comment by aminlatifi** [comment]
> Thanks @aminlatifi Seems good to me. But tests haven't passed

Thanks @mohammadranjbarz. The authentication server URL had been changed. No test action has been run since then. Pushed a commit to fix it.

**Review by CarlosQ96 — APPROVED** [review]
Thanks Amin looks good, thanks for changing urls

**Review by CarlosQ96 — APPROVED** [review]
Thanks for changing to new urls all good!

**Pull request merged**
