### PR TITLE
Fix/master test

### PR DESCRIPTION
**Pull request by aminlatifi**

### CODE REVIEW

**Review by jainkrati — APPROVED** [review]

**Comment by aminlatifi** [comment]
Can anyone look at the failed tests?! they are not related to my updates seemingly 
@mohammadranjbarz @CarlosQ96 @RamRamez @jainkrati

**Comment by mohammadranjbarz** [comment]
@aminlatifi  I have a PR that fixes the running tests problem and these test cases passed on that PR
https://github.com/Giveth/impact-graph/pull/1540

So they might be related to your changes

**Comment by aminlatifi** [comment]
> @aminlatifi I have a PR that fixes the running tests problem and these test cases passed on that PR #1540
> 
> So they might be related to your changes

@mohammadranjbarz Can you look at failed ones and the PR code. Maybe the tests fail randomly.
The way you did works, but I implemented a short general way to support running backend without replica node.

**Comment by mohammadranjbarz** [comment]
> > @aminlatifi I have a PR that fixes the running tests problem and these test cases passed on that PR #1540
> > So they might be related to your changes
> 
> @mohammadranjbarz Can you look at failed ones and the PR code. Maybe the tests fail randomly. The way you did works, but I implemented a short general way to support running backend without replica node.

Sure, let me check it

**Comment by aminlatifi** [comment]
@mohammadranjbarz I updated this with latest version of master. Let's see the result.

**Pull request merged**
