### PR TITLE
estimate matching

### PR DESCRIPTION
**Pull request by aminlatifi**
#988

### CODE REVIEW

**Comment by CarlosQ96** [comment]
Will Merge it to upgrade the main branch of Mohammad this way we can unblock frontend in dev server
I think the calculationss are correct I added new queries and helpers. Will add tests in main branch. @mohammadranjbarz

**Comment by CarlosQ96** [comment]
HOWEVER, following AMin's idea with the PR a query was made with the different parts of the formula. I think to calculate this frontend should do it, can be expensive for backend:
image

**Comment by CarlosQ96** [comment]
Or we can make a method receiving multiples values and return them all at once.

**Comment by aminlatifi** [comment]
@CarlosQ96 Thanks for finishing this PR, but there is a point. My idea was to use `getProjectDonationsSqrtRootSum` instead of `getQfRoundTotalProjectsDonationsSumExcludingProjectById` which you has created. 
First, that query is cheaper to run, and the same result can be achieved in the frontend. What do you think?
Besides, you have added to methods which would clutter the code.

**Comment by CarlosQ96** [comment]
Yeah lets optimize now, I think the first step was to unblock cherik and ramin since we had them there waiting. I think it's the correct idea to do the calculations in the frontend. I thought that would be your idea. 

However!!!!

The reason I made ```getQfRoundTotalProjectsDonationsSumExcludingProjectById``` its because if they are going to simulate the added estimated matching based on 9 dai, 10 dai , 20 dai like in the following picture:
image


They have to recalculate the total, this total, can't include the current square-root of the project since it changed. They have to add the new squareroot to the sum and to the total. 
Then subtract NewEstimateMatching - CurrentEstimatedMatching = added estimated value per donation.

That's the way I saw to calculate the image above. Or is there an easier way?

**Comment by CarlosQ96** [comment]
What do you think @aminlatifi ?

**Comment by aminlatifi** [comment]
> e way I saw to calculate the image above. Or is there an easier wa

I think there is an easier way, but I didn't explain it here, sorry for that. 
The front-end can easily calculate the square root of the project and reduce it from the total value! Then to obtain the new value do the calculation again with computing the modified square root of the project donations and and apply the different to the total sum too. @CarlosQ96 Does it make sense?

```js
const projectSquareRootSquared = Math.Power(projectSquareRoot,2);
const totalExceptProject = TotalSum -projectSquareRootSquared ;
const newProjectSquareRoot = projectSquareRoot + Math.sqrt(newDonationValue);
const newProjectSquareRootSquared = Math.power(newProjectSquareRoot, 2)
const newTotal  = totalExceptProject + newProjectSquareRootSquared
....

```

**Comment by CarlosQ96** [comment]
Yeah thanks, I overlooked that way. I agree.

**Pull request merged**
