### PR TITLE
Setup notification center disabling and reduce notifications

### PR DESCRIPTION
**Pull request by CarlosQ96**
Related to: https://github.com/Giveth/impact-graph/issues/1239

### CODE REVIEW

**Comment by CarlosQ96** [comment]
Based on the issue I removed the notifications that are owner related. 
Like owner Edited it's own project -> received a notification about this action. As said in the issue these are unnecesary.

**Comment by CarlosQ96** [comment]
Added env var that disables calls to the notification center

**Comment by CarlosQ96** [comment]
@RamRamez @MohammadPCh However the notification center SETTINGS edits are not from the impact graph. So might need to disable this view in the frontend.

**Comment by CarlosQ96** [comment]
Checklist

Remove these notifications:

- [x] 1.  Donor: Made Donation
- [x] 2.  Project Owner: Received Donation (If donation USD value is > $1)
- [x] 3.  Project Owner: My project activity - Project published
- [x] 4.  Project Owner: My project activity - Project updated or edited
- [x] 5.  General User: Project user liked: Project is now listed

Remove these emails (however simply disabling them from the impact graph should be enough). 

- [x] 1.  Project Owner: Received Donation (If donation USD value is > $1)
- [x] 2.  Donor: Made Donation

**Comment by CarlosQ96** [comment]
Once approved and merged we can cherry pick it to production. 
Remember to setup the env var to disable the calls. (this should allow us to turn off the notification center in the server without any issue).

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @CarlosQ96 
LGTM

**Review by aminlatifi — APPROVED** [review]
I have an idea, why not apply all changes upstream in the notification center adapter? I mean the methods be called by do nothing! Changes will be less and revertable/configuratble easily

**Pull request merged**
