### PR TITLE
Feature/add admin to all projects query

### PR DESCRIPTION
**Pull request by CarlosQ96**
Same as the usual project query but now you can query de adminUser
Made the implementation for the joinColumn of a existing column to be used as a foreign key.
```js
adminUser {
  id
}
```

### CODE REVIEW

**Comment by CarlosQ96** [comment]
@mohammadranjbarz fixed both pagination mini bug and added the admin to the query as a virtual attribute to be serialized by graphql. You can review now

**Comment by CarlosQ96** [comment]
The method getManyAndCount() was returning the wrong count.

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 
Are sure that your queries work?

```
  query  {
    projects {
      projects{
        title
        slug
        slugHistory
        adminUser {
          id
          firstName
        }
      }
    }
  }
```

```
query{
  projectBySlug(slug:"test-5-0"){
      id
      title
      description
      image
      slug
      creationDate
      admin
      walletAddress
      impactLocation
      qualityScore
      adminUser{
          id
    }
    reactions{
      id
      reaction
    }
      listed
      verified
      categories {
        name
      }
      status {
        id
        symbol
        name
        description
      }
  }
}
```


Screen Shot 1400-08-30 at 07 48 24
Screen Shot 1400-08-30 at 07 51 58

**Review by mohammadranjbarz — APPROVED** [review]
@CarlosQ96 
Great job, I have added this adminUser to `projects` query as well,
please update the issues, and tell @RamRamez  to test these web services

**Pull request merged**
