### PR TITLE
F 316 write test for edit projcet update

### PR DESCRIPTION
**Pull request by FatemeGhasemi**
Write test for edit projcet update
Related to #316

### CODE REVIEW

**Comment by FatemeGhasemi** [comment]
@mohammadranjbarz can you please review this?

**Review by mohammadranjbarz — APPROVED** [review]
@FatemeGhasemi Thanks, Seems good to me

**Comment by mohammadranjbarz** [comment]
@FatemeGhasemi 
Please fix conflicts

**Comment by FatemeGhasemi** [comment]
@mohammadranjbarz Done :)

**Pull request merged**
