### PR TITLE
Feature Add revoke badge cronjob (Wip)

### PR DESCRIPTION
**Pull request by CarlosQ96**
Related to https://github.com/Giveth/impact-graph/issues/371

### CODE REVIEW

**Comment by CarlosQ96** [comment]
@mohammadranjbarz This is ready for review. Let me know your feedback.

However, after that let's not merge.
Waiting on Ashley to provide a list of considerations she will talk with the verification Team first.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz This is ready for review. Let me know your feedback.
> 
> However, after that let's not merge. Waiting on Ashley to provide a list of considerations she will talk with the verification Team first.

Thanks @CarlosQ96 Very nice job, I approved your PR, but I think it's good to have another test case to check that this revoking badge automatically doesn't affect **listing** status of project

**Review by mohammadranjbarz — APPROVED** [review]

**Comment by MoeNick** [comment]
@WhyldWanderer is it still going? or we close it?

**Comment by CarlosQ96** [comment]
Ill be closing this PR and making a new one, I am getting tons of merge conflicts.

**Pull request closed without merging**
