### PR TITLE
Include non boosted projects in project power view.

### PR DESCRIPTION
**Pull request by aminlatifi**
Refs https://github.com/Giveth/giveth-dapps-v2/issues/761

### CODE REVIEW

**Comment by aminlatifi** [comment]
@mohammadranjbarz Please make this migration be run again to be run again on develop env to be sure everything will be fine after

**Review by mohammadranjbarz — APPROVED** [review]
Seems good to me

**Comment by mohammadranjbarz** [comment]
@aminlatifi  Now it's up and running on Develop server

**Comment by aminlatifi** [comment]
> @aminlatifi Now it's up and running on Develop server

Thanks @mohammadranjbarz

**Pull request merged**
