### PR TITLE
Two projects with same slug and recipient address

### PR DESCRIPTION
**Pull request by RamRamez**
#1176

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
@RamRamez  two test cases have been failed

**Comment by RamRamez** [comment]
> @RamRamez two test cases have been failed

Fixed!

**Review by mohammadranjbarz — CHANGES_REQUESTED** [review]
Thanks @RamRamez  LGTM.
But you need to add a migration file to add the unique index in the migration (because the annotations just will work on test environment, for local or production ENV you should write migration file

**Comment by RamRamez** [comment]
> Thanks @RamRamez LGTM. But you need to add a migration file to add the unique index in the migration (because the annotations just will work on test environment, for local or production ENV you should write migration file

Done!

**Comment by RamRamez** [comment]
> Thanks @RamRamez LGTM. But you need to add a migration file to add the unique index in the migration (because the annotations just will work on test environment, for local or production ENV you should write migration file

Done!

**Review by CarlosQ96 — APPROVED** [review]
LGTM but before prod merging we should check there arent duplicates and delete/modify them or else the deploy will fail in the migration

**Comment by RamRamez** [comment]
> LGTM but before prod merging we should check there arent duplicates and delete/modify them or else the deploy will fail in the migration

Yes, I've already changed the slug of duplicate projects in both staging and production

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @RamRamez nice job.

**Pull request merged**
