### PR TITLE
F 317 prevent repetitive titles for projects

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
related to Giveth/giveth-next#317

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
For testing this you should use this query

```
{
  isValidTitleForProject(title:"test Upload      pHoto")
}
```

the checking is case insensitive and escapes spaces and checks to makes sure that there is not special characters in title

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 
I have implemented a new query for validating project titles:

```
{
  isValidTitleForProject(title:"test Upload*&      pHoto")
}
```
and also I validate title before creating and updating projects
This is the test scenario, please consider the test flow while reviewing

https://github.com/Giveth/giveth-next/issues/317#issuecomment-950276960

**Comment by CarlosQ96** [comment]
Tested this scenarios and they all passed. Tried a bunch of special characters and all good:
- [x]  Title can not be repetitive
- [x] we would check the case insensitive, we if we have a project with title test we assume Test is invalid
- [x] if user put space between words we drop them when comparing ( For instance if we have a project with title test two we assume test two is invalid
- [x]  We just let the user use letters and numbers and space, no special character is permitted
- [x]  We check all this stuff in creating and updating projects

**Comment by CarlosQ96** [comment]
Just a quick question, should we allow the letter accents like 'á' and letters like Ñ for other languages? Maybe a spanish project for example. We can discuss this tomorrow. (they would be cleaned up in the slug tho)

**Comment by mohammadranjbarz** [comment]
> Just a quick question, should we allow the letter accents like 'á' and letters like Ñ for other languages? Maybe a spanish project for example. We can discuss this tomorrow. (they would be cleaned up in the slug tho)

@MoeNick  @aminlatifi 
I think we should just allow English letters, 
@aminlatifi  @MoeNick  What's your idea about what Carlos said,

**Comment by aminlatifi** [comment]
Good question, @MoeNick I guess it needs to be discussed by users (stakeholders) and be supported in front end too

**Comment by MoeNick** [comment]
> Just a quick question, should we allow the letter accents like 'á' and letters like Ñ for other languages? Maybe a spanish project for example. We can discuss this tomorrow. (they would be cleaned up in the slug tho)

If we support other languages, we have to do it's own features, it's not about just Spanish. If we open it, why we don't do it for others, assume we may allow Chinese alphabet or not? And how we choose? based on our target market? Projected amount of donations? Populations? Demographics on blockchain users worldwide? 

For example some other languages are right-left which may change the whole platform is selected.

So I thinks it's not about just adding some characters, we have to bring language capabilities in our backlog and decide when to have them gradually.

**Comment by mohammadranjbarz** [comment]
Thanks guys
As @MoeNick said, currently we just support the English letter, so I merge this PR.

**Pull request merged**
