### PR TITLE
feat: add endpoint to delete draft project

### PR DESCRIPTION
**Pull request by Reshzera**
## Summary by CodeRabbit

- **New Features**
	- Introduced functionality to delete draft projects along with related entities.
	- Added a new GraphQL mutation for deleting draft projects.
	- Enhanced user feedback with new error messages for deletion permissions.
  
- **Bug Fixes**
	- Improved test coverage for draft project deletion scenarios, ensuring accurate handling of various cases.

- **Documentation**
	- Updated localization files in English and Spanish to reflect new error messaging related to project deletion.

### CODE REVIEW

**Comment by Reshzera** [comment]
#1519

**Comment by mohammadranjbarz** [comment]
@Reshzera Can you fix the CI/CD test workflow, it's failing

**Comment by Reshzera** [comment]
@mohammadranjbarz fixed

**Comment by mohammadranjbarz** [comment]
@Meriem-B Can you review this?

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @Reshzera  great job, please resolve conflicts then merge it yourself, after you merged it, let FE guys know that you implemented it by commenting the endpoint and instruction to have call it in the issue

**Comment by maryjaf** [comment]
The frontend change related to delete draft donation hasn't been merged on staging , am I right? 
and it isn't in scope of this release ?
@Reshzera @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> The frontend change related to delete draft donation hasn't been merged on staging , am I right? and it isn't in scope of this release ? @Reshzera @mohammadranjbarz

@maryjaf Yes just the backend is on production, the FE side has not been implemented yet
https://github.com/Giveth/giveth-dapps-v2/issues/1271

**Pull request merged**
