### PR TITLE
Feature/docker tsc build scripts update

### PR DESCRIPTION
**Pull request by CarlosQ96**
Related to https://github.com/Giveth/impact-graph/issues/620

### CODE REVIEW

**Comment by CarlosQ96** [comment]
@mohammadranjbarz can you take a look when running docker compose? I am having a env var issue. After that we can do a test deploy.

**Comment by CarlosQ96** [comment]
Ready for review Mohammad. Let me know if anything needs to be changes, also if you feel like I ran the app without and with docker and adminbro runs, components render fine.
Let's do a final review and do a test deploy!

**Comment by CarlosQ96** [comment]
Btw I felt the migrations took a bit of time to run, but maybe it's because they ran from zero. 

That's my only caveat. Aside from that everything was fine.

**Comment by CarlosQ96** [comment]
Last question @mohammadranjbarz , now that I am reading a bit. Should we compile tests too? and run them from build?

I personally don't think it will speed up things, because most use the database directly, so the overhead we are having is db connections related.

If we want to optimize tests, we have to reduce/mock some database calls. But let me know what you think? and if so, we should make a separate issue for this. It's not high priority right now.

**Comment by mohammadranjbarz** [comment]
> Btw I felt the migrations took a bit of time to run, but maybe it's because they ran from zero.
> 
> That's my only caveat. Aside from that everything was fine.
You know  I think maybe we need to convert migration files to js and run them as js files, it may solve the bootstrap speed problem, I created an issue for that
https://github.com/Giveth/impact-graph/issues/651

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @CarlosQ96  for your work on this issue, LGTM

**Pull request merged**
