### PR TITLE
Feat/separate givback verfied

### PR DESCRIPTION
**Pull request by MohammadPCh**
- #1743 

## Summary by CodeRabbit

- **New Features**
  - Introduced a new Givback eligibility criterion for projects and donations, enhancing the donation processing logic.
  - Added the ability to approve projects instead of merely verifying them, streamlining project management workflows.

- **Bug Fixes**
  - Updated relevant tests and logic to reflect the changes from verification to eligibility, ensuring accurate functionality.

- **Documentation**
  - Updated documentation to clarify the new semantics surrounding project eligibility for Givback.

- **Refactor**
  - Renamed and modified parameters across various functions to align with the new eligibility focus, improving code clarity.

- **Tests**
  - Adjusted test cases to validate the new Givback eligibility logic in donations and project verification processes.

- **Chores**
  - Enhanced testing capabilities by adding new test scripts for the project Givback repository.
  - Improved error handling in migration processes to ensure robustness during execution.

### CODE REVIEW

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @MohammadPCh  LGTM

(Just please run migrations on your local machine before merging this PR)

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 Can you review it?

**Review by CarlosQ96 — APPROVED** [review]
LGTM! thanks for the tests and work!
Just make sure migrations ran good locally and can merge.

**Comment by mohammadranjbarz** [comment]
> LGTM! thanks for the tests and work! Just make sure migrations ran good locally and can merge.

Thanks man, will merge it after our release

**Comment by divine-comedian** [comment]
## notes 

changed status from verified -> givbacksEligible 
change some materialized views put migration files in another folder to make sure it runs on production. 

- existing verified projects become givbacksEligible
- front-end needs to be adjusted to look for new status when adding GIVbackseligible UI components
- mohammad will explain BE changes so we can handle FE necessary changes

**Comment by mohammadranjbarz** [comment]
@mateodaza The needed changes you should apply on FE
1. Get `isGivbackEligible` field of the project and everywhere you show anything related to givbackEligible instead of using `verified` field, use this one
2. Verification form would affect `isGivbackEligible` so when you check `verified` field to now allow create verification form , ... please use `isGivbackEligible` instead of `verified` field

Seems we just have these few changes in our API, but if you had any question please let me know

cc: @divine-comedian

**Pull request merged**
