### PR TITLE
Hotfix: add campaign manager role

### PR DESCRIPTION
**Pull request by CarlosQ96**
Related to: https://github.com/Giveth/impact-graph/issues/929

### CODE REVIEW

**Comment by MoeNick** [comment]
@mohammadranjbarz please review this one

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz please review this one

@MoeNick  PR is not ready, I have sent my feedbacks to @CarlosQ96  in DM and he is working on that

**Comment by CarlosQ96** [comment]
@MoeNick @mohammadranjbarz ready for second review, refactored all adminbro permissions and added the new role.

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @CarlosQ96  your implementation and role-permission idea was great, I tested it seems ok, I just created a PR to refactor the whole adminBro and source/target branch of that PR is your branch so after merging that, we can merge this PR

https://github.com/Giveth/impact-graph/pull/954

**Pull request merged**
